# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupyterlab_notifications_extension
project_short_description:
  JupyterLab extension that shows notifications sent by a
  JupyterHub administrator or by a script, as a toast and in the notification
  center.
python_name: jupyterlab_notifications_extension
repository: ''
test: true
