# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupyterlab_notifications_extension
project_short_description: Jupyterlab extension to receive and display notifications
    in the main panel. Those can be from the jupyterjub administrator or from other
    places.
python_name: jupyterlab_notifications_extension
repository: ''
test: true

